# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 039bbf91fac7515998a716a02d3f4a1f9b7d968cb017a9affc938e275c20c10961e310c307d4d6bdc152475b1989da3f876a3e224f190df7771e48092a55c05b

test:
  secret_key_base: 6e164eba467863f708f5ae38b468d5ffe4e939ccb90687b9a892ee5706cfaaf6e98939f866de5ad211fe70fafb3dad84838bd9ea239a21d9564b758a22cae43f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
